Creación de Schemas y Endpoints
openpolitica/proclama-preliminar pull request #40
Opened 2021-06-12 17:23 UTC by dmarquinah

Se han agregado los Schemas usados así como los endpoints para cada Schema.
`Agreements`
`Events`

Además se ha modificado la conexión hacia la BD a través de `mongoose`

2021-06-12 17:39 UTC, dmarquinah commented on util/mongodb.js
> +import mongoose from 'mongoose';
Uso de librería `mongoose` referenciado en otros archivos.

2021-06-12 17:39 UTC, dmarquinah commented on util/mongodb.js
> +      useCreateIndex: true,
Creación de Indexes en caso sea necesario

2021-06-12 17:39 UTC, dmarquinah commented on util/mongodb.js
> +        isConnected: client.connections[0].readyState,
Estado de la conexión, válido para verificación o reconexión.

2021-06-12 17:40 UTC, dmarquinah commented on pages/api/agreements/index.js
> +        const agreements = await AgreementsSchema.find({}).populate('events');
El resultado del query devuelve los Acuerdos y el array de Eventos (si tuviera)

2021-06-12 17:43 UTC, dmarquinah commented on pages/api/events/[id].js
> +    query: { id },
Usar el query para `id` para buscar un evento en específico, hace referencia a la propiedad `_id` creada nativamente por mongoose.

2021-06-12 17:44 UTC, dmarquinah commented on pages/api/events/index.js
> +        const newEvent = await EventsSchema.create(new EventsSchema(body));
El nombre de los keys en el `body` deberán coincidir con los keys en el Schema.

2021-06-13 19:36 UTC, wixo requested changes
Gracias @dmarquinah! Creo que vamos por buen camino, veo funcionando varias cosas.

2021-06-13 19:36 UTC, wixo commented on models/Events.js
> +  agreement: {
De repente agreement_id? así queda más explicito.

2021-06-13 19:36 UTC, wixo commented on models/Events.js
> +    enum: ['Si cumple', 'No cumple', 'Alto riesgo'],
De repente podríamos tener el enum con valores en inglés, para mantener la consistencia con el código:
```suggestion
    enum: ['yes', 'no', 'risk'],
```

2021-06-13 19:36 UTC, wixo commented on models/Events.js
> +  political_party: {
Podríamos ponerle un default hacia "Perú Libre" si no indicado? y también creo que convendría un enum con los 2 nombres `['Perú Libre', 'Fuerza Popular']`.

2021-06-13 19:36 UTC, wixo commented on pages/api/agreements/index.js
> +    // case 'POST':
Creo que no vamos a agregar Acuerdos ni ahora ni en el futuro, podríamos prescindir de este comment en su totalidad.

2021-06-13 19:36 UTC, wixo commented on pages/api/events/index.js
> +        const newEvent = await EventsSchema.create(new EventsSchema(body));
Cool, pude crear un Evento con Postman, ahora, la idea es que este método solo este disponible internamente (parecido a lo que se hizo en `signatures/index.js`, conversémoslo por interno.

2021-06-13 19:36 UTC, wixo commented on pages/api/agreements/index.js
> +import AgreementsSchema from '../../../models/Agreements';
NextJS nos permite usar rutas absolutas al baseUrl
```suggestion
import { connectToDatabase } from 'util/mongodb';
import AgreementsSchema from 'models/Agreements';
```

2021-06-13 19:36 UTC, wixo commented on pages/api/events/[id].js
> +import EventsSchema from '../../../models/Events';
```suggestion
import { connectToDatabase } from 'util/mongodb';
import EventsSchema from 'models/Events';
```

2021-06-13 19:36 UTC, wixo commented on pages/api/events/index.js
> +import AgreementsSchema from '../../../models/Agreements';
```suggestion
import { connectToDatabase } from 'util/mongodb';
import EventsSchema from 'models/Events';
import AgreementsSchema from 'models/Agreements';
```

2021-06-14 00:38 UTC, LuighiV commented on pages/api/events/index.js
> +          { id: body.agreement },
Hola @dmarquinah , como se ha cambiado el esquema de `agreement` a `agreement_id`, creo que también debería cambiarse aquí.

2021-06-14 01:17 UTC, dmarquinah commented on pages/api/events/index.js
> +          { id: body.agreement },
Gracias por darte cuenta 👍

2021-06-14 03:43 UTC, merged