Adiciona formulario para actualización de eventos
openpolitica/proclama-preliminar pull request #42
Opened 2021-06-14 04:35 UTC by LuighiV

- Utiliza el contraseña para iniciar sesión.
- Se crea una página de inicio de sesión solamente para ingreso de contraseña. Se verifica si la contraseña es correcta o no y se muestra un mensaje en caso que no lo sea.
- Cuando se ingresa a `update-form/` se redirige automáticamente a `update-form/login` para ingresar los datos.
- Se crea una página de formulario para ingresar los datos correspondientes al evento. Al hacer clic en actualizar, se conecta con la base de datos mediante una llamada a la API y actualiza la información mostrando un mensaje con el prompt y una vista de resumen con la información enviada.  En la vista de resumen se tiene un botón para regresar a la vista de envío de nueva actualización.
- Tanto en la vista de formulario como la vista de resumen se tiene un botón para cerrar la sesión.
- Solamente se puede hacer llamados a la API mientras se haya iniciado sesión. 

La variable requerida para la contraseña en el lado del servidor es `UPDATE_PWD`.

Closes #33 
Closes #34

2021-06-15 03:34 UTC, wixo requested changes
Solo revisar lo de la data de agreements, debería ser el pedido de la bd para solo tener una fuente de verdad. Gracias @LuighiV, buena chamba! 🙌 

Hay algunos componentes que podrían reusarse, como el footer, pero puedo entender las ganas de separarlos.

2021-06-15 03:34 UTC, wixo commented on components/Form/index.js
> +import { agreements } from 'data/agreements';
Esto podría ser un pedido a la base de datos, en teoría la carpeta `data` va a ser removida.

2021-06-15 03:34 UTC, wixo commented on components/Form/index.js
> +      id: 'status_yes',
podríamos prescindir de snake_case pero no lo veo importante.

2021-06-15 15:41 UTC, LuighiV commented on components/Form/index.js
> +import { agreements } from 'data/agreements';
Resuelto en 
bcf81d2

2021-06-15 15:41 UTC, LuighiV commented on components/Form/index.js
> +      id: 'status_yes',
Resuelto en
bcf81d2

2021-06-16 03:35 UTC, wixo approved these changes

2021-06-16 03:35 UTC, wixo commented on pages/update-form/index.js
> +      // https://github.com/vercel/next.js/issues/11993#issuecomment-617375501
😯

2021-06-16 03:35 UTC, merged