Add Home page
openpolitica/proclama-preliminar pull request #6
Opened 2021-05-21 01:31 UTC by AlmeAld

Closes #4 

![image](https://user-images.githubusercontent.com/60791759/119068705-57969f80-b9aa-11eb-80a0-1372119a59b3.png)

2021-05-21 01:55 UTC, LuighiV reviewed
Hola @AlmeAld, el deployment ha fallado porque la versión de svgo no está actualizada. No sé por qué npm no obtiene la última versión. Por favor, cambiarlo a la versión 2.3.0. También puedes poner el download-icon.svg en la lista `blacklist` de `scripts/optimize-svg.js`.

Otro detalle es que los logos de 200 y transparencia se ven como difuminados, no si se deberá a la calidad del logo.

2021-05-21 03:24 UTC, wixo requested changes
Hola @AlmeAld, muchas gracias por enviar este PR es un avance muy significativo, el código presentado está ordenado y es fácil de entender 🙌. Dejé comentarios sobre detalles, salvando eso lo demás me parece super cool! 🚀

2021-05-21 03:24 UTC, wixo commented on components/Footer/index.js
> +function index() {
Interesante que deje poner el nombre en minúscula, qué te parece cambiarlo a 
```suggestion
function Footer() {
```
No habrá colisión con la línea 5 porque es `<Styled.Footer>` :D

2021-05-21 03:26 UTC, wixo commented on pages/_app.js
> +        <link
Me olvidé de mencionar, en Figma también está el uso de la tipografía `Inter` para https://github.com/openpolitica/proclama-preliminar/pull/6/files#diff-f390548dfb5cb043fdbe6972313158c14f60695bd4b780dc13f25e2373448289R39

2021-05-21 03:48 UTC, wixo commented on components/Home/styles.js
> +  font-weight: bold;
@LuighiV me comentá que ahí no se ejecutó el linter por la línea comentada. FYI.

2021-05-21 05:44 UTC, AlmeAld commented on components/Footer/styles.js
> +  font-size: 20px;
ok, se me pasó

2021-05-21 05:45 UTC, AlmeAld commented on components/Home/styles.js
> +  font-weight: bold;
si, gracias @LuighiV y @wixo

2021-05-21 06:26 UTC, AlmeAld commented on components/Home/index.js
> +        <Styled.DownloadContent>
gracias @wixo, sigo sufriendo con los nombres jejeje

2021-05-22 04:51 UTC, merged

2021-05-22 04:52 UTC, wixo commented
Muchas gracias @AlmeAld!!!! 🚀