Update agreement card
openpolitica/proclama-preliminar pull request #90
Opened 2022-01-23 16:03 UTC by LuighiV

- Delete alert
- Delete description
- Link see more to agreement page

2022-01-26 20:40 UTC, wixo requested changes
Gracias @LuighiV, 2 preguntas.

2022-01-26 20:40 UTC, wixo commented on components/AgreementCard/index.js
> +  const [expanded] = useState(false);
Pienso que deberíamos de borrar `expanded` también, a menos que se esté usando en otro lado.

2022-01-26 20:40 UTC, wixo commented on components/AgreementCard/index.js
> +import { Card, Number, Title, SeeMore } from './styles';
Deberíamos borrar el código de `Description` de `./styles`?

2022-01-26 21:38 UTC, LuighiV commented on components/AgreementCard/index.js
> +  const [expanded] = useState(false);
Si, me había olvidado ya está en bcd4af9

2022-01-26 21:38 UTC, LuighiV commented on components/AgreementCard/index.js
> +import { Card, Number, Title, SeeMore } from './styles';
Sip, está bien, lo agregué en bcd4af9

2022-01-31 22:37 UTC, wixo approved these changes
Gracias @LuighiV! 🙌

2022-01-31 22:37 UTC, merged